### PR TITLE
Add images based on MariaDB.

### PR DESCRIPTION
**Pull request by slashrsm**
More and more people (incl. myself) prefer using MariaDB over MySQL.

We will need to update configuration on Docker hub when this gets in.

### CODE REVIEW

**Comment by zaporylie** [comment]
What you think about having Dockerfiles for Mysql and MariaDB in separate repos?

Pros:
- consistent naming convention (drupaldocker/mysql:_version_ <=> drupaldocker/mariadb:_version_)
- Automated Build on Docker Hub can rebuild image if parent one will change

Cons:
- drupal.cnf has to be synchronised across repos (we could leave inline comment to remember about that)

I created https://github.com/drupal-docker/mariadb, basic structure and docker hub and travis integration. 

Also remember to change value for `MAINTAINER` in Dockerfile to from my nickname to `drupal-docker`.

**Comment by slashrsm** [comment]
I generally prefer if things are not fragmented to much. I even think that drupal-docker/drush actually belong in drupal-docker/php.

> Automated Build on Docker Hub can rebuild image if parent one will change Cons:

We can still have separate automated builds on hub if we have a single repository. This also allows us to correctly configure triggers when upstream changes. 

> drupal.cnf has to be synchronised across repos (we could leave inline comment to remember about that)

I think this is a con, not a pro.

**Comment by zaporylie** [comment]
> I think this is a con, not a pro.

Yes, definitely a con. I fixed markdown for my comment :+1: Also added a comment to drupal.cnf

> We can still have separate automated builds on hub if we have a single repository. This also allows us to correctly configure triggers when upstream changes.

screen shot 2016-02-19 at 09 56 19

I know I could add MariaDB to "Repository Links" section as well but then mysql would be updated based on mariadb changes. It's not a big deal, I know, but I like to keep things clean.

**Comment by slashrsm** [comment]
I was thinking about two separate namespaces on Docker hub (drupaldocker/mysql and drupaldocker/mariadb) both pointing to the same repository on Github (drupal-docker/mysql). This way you'd be able to configure separate repository links for each of those. 

Anyway. This is not of huge importance.

**Comment by zaporylie** [comment]
Yeah, I know you can do that but:
- Docker Hub builds only one image at the time, i.e. for php it take over an hour to build all images
- If you do even small change to one Dockerfile (or Readme, doesn't matter) in your repo all images has to be built again.
- ...in that case for both mysql and mariadb.
- More Dockerfiles we have in one repo, more time it takes to complete build.
- The same for Travis, it has to built pull request before I can merge it and yesterday it took several hours to complete tests just because queue was so long.

Conclusion - less is better :)

Anyway - thank you for your patience!

**Pull request closed without merging**
